<section>
    <a href="zakaznik/<?= $pojistka['id_zakaznika'] ?>">Zpět</a>
    <h2><?= $pojistka['nazev'] ?></h2>
    <h3>Jednatel: <?= $pojistka['jmeno'] . " " . $pojistka['prijmeni'] ?></h3>
    <div class="obrazek">
        <img src="img/<?= $pojistka['obrazek'] ?>.png" alt="<?= $pojistka['obrazek'] ?>">
        <p><?= $pojistka['popis'] ?></p>
    </div>
    <div>        
        <h3><?= $pojistka['jmeno_zakaznika'] . " " . $pojistka['prijmeni_zakaznika'] ?></h3>
        <p>Pojištěno od: <?= $zacatek = date('d.m.y.', strtotime($pojistka['od'])) . " do " . $konec = date('d.m.y.', strtotime($pojistka['do'])) ?> Měsíční poplatek: <?= $pojistka['cena'] ?> Kč</p>
         </h3>
    </div>
    
</section>