<section>
    <a href="zakaznik/<?= $zakaznik['id_zakaznika'] ?>">Zpět</a>
    <h2>Upravit data zakaznika</h2>
    <form method="post">
        <input type="hidden" name="id_zakaznika" value="<?= $zakaznik['id_zakaznika'] ?>">
        <label for="jmeno_zakaznika">
            Jméno <br />
            <input type="text" name="jmeno_zakaznika" value="<?= $zakaznik['jmeno_zakaznika'] ?>"><br />
        </label>
        <label for="prijmeni_zakaznika">
            Příjmení <br />
            <input type="text" name="prijmeni_zakaznika" value="<?= $zakaznik['prijmeni_zakaznika'] ?>"><br />
        </label>
        <label for="email_zakaznika">
            Email <br />
            <input type="email" name="email_zakaznika" value="<?= $zakaznik['email_zakaznika'] ?>"><br />
        </label>
        <label for="mesto">
            Město <br />
            <input type="text" name="mesto" value="<?= $zakaznik['mesto'] ?>"><br />
        </label>
        <label for="ulice">
            Ulice <br />
            <input type="text" name="ulice" value="<?= $zakaznik['ulice'] ?>"><br />
        </label>
        <label for="cp">
            Číslo popisné <br />
            <input type="text" name="cp" value="<?= $zakaznik['cp'] ?>"><br />
        </label>
        <label for="psc">
            PSČ <br />
            <input type="number" name="psc" value="<?= $zakaznik['psc'] ?>"><br />
        </label>
        <label for="narozeni">
            Datum narození<br />
            <input type="date" name="narozeni" value="<?= $zakaznik['narozeni'] ?>"><br />
        </label>
        <input type="submit" value="Uložit" />
    </form>

</section>