<h1>Editor Produktu</h1>
<form method="post">
    <input type="hidden" name="id_produktu" value="<?= $produkt['id_produktu'] ?>" />
    <label for="nazev">
        Nazev<br />
        <input type="text" name="nazev" value="<?= $produkt['nazev'] ?>" />
    </label><br />
    <label for="popis">
        Popis<br />
        <textarea id="popis" name="popis"><?= $produkt['popis'] ?></textarea>
    </label><br />
    <label for="obrazek">
        Obrazek<br />
        <input type="text" name="obrazek" value="<?= $produkt['obrazek'] ?>" />
    </label><br />
    <input type="submit" value="Uložit" />
</form>

<script src="/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="/tinymce/js/tinymce/jquery.tinymce.min.js"></script>

<script type="text/javascript">
    // Nastavení použité pro TinyMCE 5.7.1
    tinymce.init({

        selector: '#obsah', // Alternativní zápis: `selector: 'textarea[name=obsah]'` nebo pouze `selector: 'textarea'`
        language: 'cs',
        toolbar_mode: 'sliding',

        // Doporučené, vypíná převod české diakritiky na entity, šetří místo v tabulce, chceme text formátovat do html tagů
        entities: '160,nbsp',
        entity_encoding: 'named',

        // Doporučené
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],

        // Doporučené
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    });
</script>