<section>
    <form method="post"> 
        <label for="jmeno_zakaznika">
            Jméno <br/>
            <input type="text" name="jmeno_zakaznika"><br/>
        </label>
        <label for="prijmeni_zakaznika">
            Příjmení <br/>
            <input type="text" name="prijmeni_zakaznika"><br/>
        </label>
        <label for="email_zakaznika">
            Email <br/>
            <input type="email" name="email_zakaznika"><br/>
        </label>
        <label for="mesto">
            Město <br/>
            <input type="text" name="mesto"><br/>
        </label>
        <label for="ulice">
            Ulice <br/>
            <input type="text" name="ulice"><br/>
        </label>
        <label for="cp">
            Číslo popisné <br/>
            <input type="text" name="cp"><br/>
        </label>
        <label for="psc">
            PSČ <br/>
            <input type="number" name="psc"><br/>
        </label>
        <label for="narozeni">
            Datum narození<br/>
            <input type="date" name="narozeni"><br/>
        </label>
        <input type="submit" value="Uložit" />
    </form>
   
</section>