<section>
    <a href="zakaznik/<?= $zakaznik['id_zakaznika'] ?>">Zpět</a>
    <h2>Založení pojištění pro <?= $zakaznik['jmeno_zakaznika'] ?></h2>
    <p>Jednatel <strong><?= $uzivatel['jmeno'] ?> <?= $uzivatel['prijmeni'] ?></strong>
    <p>Pojišťovaný <strong><?= $zakaznik['jmeno_zakaznika'] ?> <?= $zakaznik['prijmeni_zakaznika'] ?></strong></p>

    <div style="display: flex">
        <div>
            <form action="pojistit" method="post">
                <input type="hidden" name="id_produktu" value="<?= $produkt['id_produktu'] ?>">
                <input type="hidden" name="id_uzivatele" value="<?= $uzivatel['id_uzivatele'] ?>">
                <input type="hidden" name="id_zakaznika" value="<?= $zakaznik['id_zakaznika'] ?>">
                <h3>Pojistit na období</h3>            
                <label for="produkt">Vyberte druh pojištění:
                    <select name="id_produktu" id="id_produktu">
                        <?php foreach ($produkty as $produkt) : ?>
                            <option value="<?= $produkt['id_produktu'] ?>"><?= $produkt['nazev'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </label> <br/>
                <label for="od">
                    Pojistit od <br />                    
                    <input type="date" name="od"><br />
                </label>
                <label for="do">
                    Pojistit do <br />
                    <input type="date" name="do"><br />
                </label>
                <label for="cena">
                    Částka za měsíc v Kč <br />
                    <input type="number" name="cena"><br />
                </label>
                <input type="submit" name="pojistit" value="Pojistit">
            </form>
        </div>
    </div>
</section>
