<section>
    <a href="pojistovna">Zpět</a>
    <h1>Prosím přihlaste se</h1>
    <div style="display : flex">
        <form method="post">
            <label>
                Email<br />
                <input type="text" name="email" />
            </label><br />
            <label>
                Heslo<br />
                <input type="password" name="heslo" />
            </label><br />
            <input type="submit" value="Přihlásit" />
        </form>
        <div class="obrazek">
            <img src="./img/who.png" alt="Přihlásit" >
        </div>
    </div>
    <p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>
</section>
