<section>
    <a href="pojistovna">Zpět</a>
    <h1>Registrace</h1>
    <form method="post">
        <label>
            Jméno<br />
            <input type="text" name="jmeno" />
        </label><br />
        <label>
            Příjmení<br />
            <input type="text" name="prijmeni" />
        </label><br />
        <label>
            Email<br />
            <input type="email" name="email" />
        </label><br />
        <label>
            Heslo<br />
            <input type="password" name="heslo" />
        </label><br />
        <label>
            Heslo znovu<br />
            <input type="password" name="heslo_znovu" />
        </label><br />
        <label>
            Zadejte aktuální rok (antispam)<br />
            <input type="text" name="rok" />
        </label><br />
        <input type="submit" value="Registrovat" />
    </form>
</section>


